### ISSUE TITLE
USE_TENCLICK_THERMAL_CONFIG is Obsolete

### ISSUE THREAD

**Issue by GarikFirst** [loneoceans/lume1-fireflies#1]
USE_TENCLICK_THERMAL_CONFIG is Obsolete due to new logic how config menus work (with hold and scroll) and can be removed from cfg-fireflies-lume1.h

**Comment by loneoceans** [comment]
Thanks for the note and apologies for the (very) late response! Support for this driver has been ported over to the official Anduril repository and just awaiting the pull request to be merged (https://github.com/ToyKeeper/anduril). Thank you.

**Comment by loneoceans** [comment]
Thanks for the note and apologies for the (very) late response! Support for this driver has been ported over to the official Anduril repository and just awaiting the pull request to be merged (https://github.com/ToyKeeper/anduril). Thank you.
